schema_version: 1

shared:
  dataset: datasets/20250218_ilc_nnqq_sgvnew_parquet
  data_extension: parquet
  checkpoint: checkpoints/pretrained/ilc_nnqq_sgvnew_3cat_cut/net_best_epoch_state.pt
  initial_epoch: 17
  initial_state: checkpoints/pretrained/ilc_nnqq_sgvnew_3cat_cut/net_epoch-17_state.pt
  initial_optimizer: checkpoints/pretrained/ilc_nnqq_sgvnew_3cat_cut/net_epoch-17_optimizer.pt
  initial_optimizer_mode: damped
  initial_optimizer_damping: 0.25
  data_config: checkpoints/pretrained/ilc_nnqq_sgvnew_3cat_cut/data_config.auto.yaml
  network_config: networks/pretrained_sgv_particle_transformer.py
  training_controller: null
  seed: 12345
  generations: 24
  weaver_epochs_per_generation: 1
  samples_per_epoch: 2400000
  samples_per_epoch_val: 150000
  batch_size: 1024
  optimizer: ranger
  lr_scheduler: none
  num_workers: 1
  fetch_step: 0.01
  prefetch_factor: 4
  use_amp: true
  amp_dtype: fp16
  no_remake_weights: true
